version: '3.8'

services:
  bot:
    build: .
    container_name: document_bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
